# Generated by Django 5.1.1 on 2024-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_areaprofile_doctorprofile_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='uaadhar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uaadhar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
