# Generated by Django 5.1.1 on 2024-10-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_doctorprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='areaprofile',
            name='pemail',
        ),
        migrations.RemoveField(
            model_name='areaprofile',
            name='pmobile',
        ),
        migrations.AddField(
            model_name='areaprofile',
            name='opd_types',
            field=models.ManyToManyField(blank=True, to='base.opdtype'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='opd_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opdtype'),
        ),
    ]
