# Generated by Django 5.1.1 on 2024-10-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='unique_code',
        ),
    ]
