# Generated by Django 5.1.1 on 2024-10-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
