# Generated by Django 5.1.1 on 2024-10-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaprofile',
            old_name='paddress',
            new_name='uaddress',
        ),
        migrations.RenameField(
            model_name='areaprofile',
            old_name='pname',
            new_name='uname',
        ),
    ]
