# Generated by Django 5.1.1 on 2024-10-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening')], max_length=1)),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Canceled'), ('P', 'Pending')], default='P', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_profile',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Canceled'), ('P', 'Pending')], default='B', max_length=1),
        ),
    ]
