# Generated by Django 5.1.1 on 2024-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_appointment_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Canceled'), ('A', 'Available')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Canceled'), ('A', 'Available')], default='A', max_length=1),
        ),
    ]
