# Generated by Django 5.1.1 on 2024-10-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='area_profile',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='district',
        ),
    ]
