# Generated by Django 5.1.1 on 2024-10-25 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_appointment_area_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='opd_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opdtype'),
        ),
    ]
