# Generated by Django 5.1.1 on 2024-10-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_appointment_area_profile_appointment_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='area_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.areaprofile'),
        ),
    ]
